services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html  
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - network

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file:
      - .env
    networks:
      - network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/kasakh/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/kasakh/data/mariadb
      o: bind

networks:
  network:
    driver: bridge